services:
  react-app:
    container_name: viewer
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "3000"  # internal only (not exposed outside)
    volumes:
      - "./index.js:/app/index.js"
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_SERVER=${DB_SERVER}
      - DB_DATABASE=${DB_DATABASE}
      - DB_PORT=${DB_PORT}
    restart: unless-stopped

  caddy:
    image: caddy:2
    container_name: caddy
    ports:
      - "3000:80"  # external access goes through Caddy
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    environment:
      - CADDY_USER=${CADDY_USER}
      - CADDY_PASSWORD_HASH=${CADDY_PASSWORD_HASH}
